### ISSUE TITLE
Disable YAML references

### ISSUE THREAD

**Issue by moltar** [webiny/github-actions-wac#4]
When reusing chunks (as JS objects), YAML package will define repeated objects as a YAML reference.

I think that is ok, since they are meant to be machine readable. But I still think it diminishes DX, as the final workflows are not easily readable by a human (for verification purposes).

I defined a step as a JS object, and then included it twice into `steps` array:

![image](https://user-images.githubusercontent.com/491247/184630851-69ddddd8-63b4-49d6-a263-e53222bce4bc.png)

**Comment by adrians5j** [comment]
Hey @moltar, sorry for delay. These GitHub notifications just don't do it for me 😓 .

In any case, yeah, interesting. But that's how the YAML lib does it actually. Maybe there's a way to instruct it not to do this? 🤔

**Comment by moltar** [comment]
There's an option to turn this behaviour off

https://www.npmjs.com/package/js-yaml

```
 noRefs (default: false) - if true, don't convert duplicate objects into references
```
