### ISSUE TITLE
Created a package based on yours

### ISSUE THREAD

**Issue by emmanuelnk** [webiny/github-actions-wac#5]
First off, I want to thank you for your awesome work. 

I had wanted to create something like this for a while now but I was stuffed and busy. Then I came across your package and it was solving a ton of my issues. I used it in some private projects and then started hitting upon some issues (we had tight naming conventions for workflow files etc). Instead of creating multiple issues since I had no idea when they'd get addressed, I forked it and started making adjustments with the intention to make multiple PRs. At some point these adjustments grew to _very many adjustments_ and I wasn't sure that making a PR was the right move anymore (I was changing a lot of the fundamentals).

So ultimately I created my own package based on yours: https://github.com/emmanuelnk/github-actions-workflow-ts (credits at the bottom) that added more of the functionality I was looking for.

That's all. Just wanted to give credit and a heads up.

Will close this issue immediately.

**Comment by adrians5j** [comment]
🎉
